### ISSUE TITLE
service[codedeploy-agent]: unable to locate the init.d script!

### ISSUE THREAD

**Issue by eugenemiretsky** [awslabs/aws-codedeploy-samples#14]
package "codedeploy-agent" fails to create the init.d file. 

Running yum install manually creates the init.d file successfully? 

Any idea how to fix this?

**Comment by yubangxi** [comment]
Hi,

Can you add more details like the agent version and the platform. Basically any information that can help us reproduce the error. So that we can try to root cause the problem and get a fix out.

Thanks!
