### ISSUE TITLE
Lowering min desired capacity

### ISSUE THREAD

**Issue by russellneufeld** [awslabs/aws-codedeploy-samples#19]
In your examples, if the scripts decide to lower the minimum desired capacity when putting an instance into standby mode, I don't see it ever returning that minimum to the original value.  Seems a like a problem that could come back to bite you long term, as your auto-scale group could get smaller and smaller.

**Comment by matthewdfuller** [comment]
+1 - this was a problem for me too - autoscaling group min eventually went to 0 and the scale down for low ELB latency completely killed everything.

**Comment by matthewdfuller** [comment]
@russellneufeld adding the following to "common_functions.sh" at line 190 worked for me:

```
msg "Checking to see if ASG $asg_name will let us increase desired capacity"
    local min_desired=$($AWS_CLI autoscaling describe-auto-scaling-groups \
        --auto-scaling-group-name $asg_name \
        --query 'AutoScalingGroups[0].[MinSize, DesiredCapacity, MaxSize]' \
        --output text)

    local min_cap=$(echo $min_desired | awk '{print $1}')
    local max_cap=$(echo $min_desired | awk '{print $3}')
    local desired_cap=$(echo $min_desired | awk '{print $2}')

    if [ -z "$min_cap" -o -z "$desired_cap" -o -z "$max_cap" ]; then
        msg "Unable to determine minimum, maximum, and desired capacity for ASG $asg_name."
        msg "Attempting to increase the minimum regardless."
    elif [ $min_cap -lt $max_cap ]; then
        local new_min=$(($min_cap + 1))
        msg "Incrementing ASG $asg_name's minimum size to $new_min"
        msg $($AWS_CLI autoscaling update-auto-scaling-group \
            --auto-scaling-group-name $asg_name \
            --min-size $new_min)
        if [ $? != 0 ]; then
            msg "Failed to increase ASG $asg_name's minimum size to $new_min. Ensure correct minimum before proceeding."
            return 1
        fi
    fi
```

**Comment by russellneufeld** [comment]
Thanks Matt!  I’ll give this a try.

**Comment by scottharrisaus** [comment]
@matthewdfuller using the logic above can cause your min_cap to increase when it was never reduced.

ie Before putting instance into standby : Min=1, Max=2, Desired=2
The logic is : ($min_cap == $desired_cap -a $min_cap -gt 0) for determining to reduce min_cap,  so in this example min will stay set to 1.
Then your logic above will compare min to max (1 < 2) so you will then increase min to 2 which is not what you want.

I think there is no way to work out if you need to increase on taking instance out of standby unless you save the min/max in the autoscaling_enter_standby() function. Im thinking I will write these out to a file and then restore in the autoscaling_exit_standby() function.

**Comment by matthewdfuller** [comment]
@scottharrisaus good catch - honestly this seems like an excessively large script to include and maintain with every project that uses CodeDeploy. Would prefer that AWS include an option for managing instance removal / addition during the deployment process. But for now, I agree, it'll likely come down to saving the pre-deploy settings to a file and then restoring them afterwards.

**Comment by russellneufeld** [comment]
Writing these values to a file seems like the better way of ensuring they get preserved.  Please let me know when this change is made.  Thanks!

**Comment by nemo** [comment]
Hey @scottharrisaus – any updates on this?

Currently, I'm creating a file to check if the capacity was decremented before incremeneting it again before putting the instance back to InService state.

But I would far rather trust your code than mine here :P

**Comment by suryanarayanan** [comment]
@scottharrisaus @nemo @matthewdfuller  You are welcome to submit a pull request and I'd be happy to review and merge it in. Meanwhile I've added this to our backlog. Thanks.

**Comment by Poil** [comment]
+1

**Comment by suryanarayanan** [comment]
This is fixed in https://github.com/awslabs/aws-codedeploy-samples/commit/e1e1501dc44084d6e7c0857ee84279061db73e80

**Comment by russellneufeld** [comment]
Thanks!

**Comment by sreenath007** [comment]
Instead of putting the instance in standby, cant we suspend autoscaling. The deployment flow in this case will be:
suspend autoscaling
deregister first instance from elb
stop the application
deploy the code
start the application
register the instance to elb
resume autoscaling.

Does this work instead of putting instance to standby as already minimum and desired capacity is same in my autoscaling group. So after putting instance to standby, the script fails to reduce the desired capacity as it cannot go below min capacity. This cause a new instance to spin up and orginal instance to remain in standby.
