### ISSUE TITLE
Zero downtime deployments not really zero downtime

### ISSUE THREAD

**Issue by johnae** [awslabs/aws-codedeploy-samples#22]
As described here by me (and the original poster) https://forums.aws.amazon.com/thread.jspa?messageID=639390

It seems there is some downtime while deploying. It may not be the fault of code deploy but I still figured it may be an issue since the claim in the blog post here: https://blogs.aws.amazon.com/application-management/post/Tx39X8HM93NXU47/Use-AWS-CodeDeploy-to-Deploy-to-Amazon-EC2-Instances-Behind-an-Elastic-Load-Bala is that the deploy IS one without downtime. I suspect it may be more an ELB issue than code deploy though.

**Comment by Jmcfar** [comment]
Hi,

Thanks for the report! I've reached out to the ELB team to get more information about the issue and will track any updates needed to our sample in this issue.

**Comment by johnae** [comment]
Thank you. We have since moved to a different deployment strategy that is several times faster than adding/removing instances from ELBs (in our case via autoscaling standby). This is still an issue when scaling up/down though since that does trigger adding/removing instances from ELBs.

**Comment by nestorpina** [comment]
Hi @johnae , can you elaborate more? I'm really interested in this.

I was under the impression that the code example in this repo uses standby when doing deployments to ASG deployment groups, but that also implies implicitly removing the instances from the ELB. Do you refer to that? or are you using other strategy an the scripts can be improved?

Thanks in advance!

**Comment by johnae** [comment]
@nestorpina I assume you're interested in how we do deployments today? I guess it might depend on your application but here we build docker containers. In our case we just tar them up in our CI system when tests are green and put the artifact on S3. Those are used by CodeDeploy. The way we've sped up our deployments is not related to docker however. Since we use nginx (version 1.9.2+) we can utilize the new support for SO_REUSEPORT (in Linux kernel since 3.9).

That way we can have two nginx servers listening on the same ip/port concurrently. That's how we do zero-downtime deployments today.

Now we are able to deploy to AllAtOnce (with CodeDeploy) without talking to ASG:s or ELB:s with zero downtime. Deployments now take around 25 seconds as opposed to 3-4 minutes before. It's a vast improvement. And with AllAtOnce we're now limited only by the slowest deploy rather than by how many servers are running.

As I mentioned, there's still the issue of autoscaling adding/removing instances from ELB:s where we've occasionally seen dropped connections. Unfortunately that's out of our control.

**Comment by johnae** [comment]
@nestorpina For more information on the support for this in nginx, see: https://www.nginx.com/blog/socket-sharding-nginx-release-1-9-1/

**Comment by nestorpina** [comment]
@johnae Thank for the reply! That sound pretty cool, I'll have a look at the reuse_port functionality. We also use nginx so I'll definitely give it a try.

**Comment by suryanarayanan** [comment]
Hi,
The original issue with the ELB should be fixed now. Feel free to reopen if you see the connection drop again.

**Comment by tylerbenson** [comment]
One problem I have with the current solution is how the instance entering standby drops out of the elb before the replacement instance has a chance to come online. If you're deploying to a group that is near critical, removing an instance can result in downtime.  It should wait until the replacement instance is healthy before continuing.

**Comment by aws-turpiej** [comment]
The ELB team has released their fix for this issue last week.
