### ISSUE TITLE
ELB retrieval functionality broken for instances outside of ASG

### ISSUE THREAD

**Issue by mpantelimon** [awslabs/aws-codedeploy-samples#31]
Pull request #17 broke the ELB retrieval functionality for instances which are not part of an Auto Scaling group.

I am referring to function "get_elb_list()" in file "load-balancing/elb/common_functions.sh", broken by commits 7f9cdd2 and 5ab0577 from 04.09.2015. This function now displays the “list index out of range” error message for the aforementioned type on instances.

**Comment by Jmcfar** [comment]
Hi,

Thanks for the bug report. We've pushed a fix to this so you should now be able to use this for non-AutoScaling instances again.
