### ISSUE TITLE
Suspend ASG rebalance

### ISSUE THREAD

**Issue by nwalke** [awslabs/aws-codedeploy-samples#46]
We have an issue where the ASG will rebalance across AZs while we're in the middle of a deploy.  For example, we have four instances...
1 in a, 1 in b, and 2 in c. 

If the deploy starts with the instance in a, then the ASG will immediately start trying to rebalance across AZs.  This causes an instance to come up with an old version of code since the new version has not yet successfully deployed.

**Comment by eltone** [comment]
@nwalke do you have the ASG health check set to EC2 or ELB?

**Comment by nwalke** [comment]
@eltone ELB.  As far as I understand the AZ rebalance though, that shouldn't matter...?

**Comment by nwalke** [comment]
I think this is fixed by #45
