### ISSUE TITLE
Instance being added to ASG fails due to inability to move a pending instance to standby

### ISSUE THREAD

**Issue by chriskinsman** [awslabs/aws-codedeploy-samples#50]
[stderr]Running AWS CLI with region: us-west-2
[stderr]Started deregister_from_elb.sh at 2016-08-17 18:11:31
[stderr]Checking if instance i-eba9fd36 is part of an AutoScaling group
[stderr]Found AutoScaling group for instance i-eba9fd36: FrontEndASG
[stderr]Checking that installed CLI version is at least at version required for AutoScaling Standby
[stderr]Checking minimum required CLI version (1.3.25) against installed version (1.9.15)
[stderr]Attempting to put instance into Standby
[stderr]Checking if this instance has already been moved in the Standby state
[stderr]Checking to see if ASG FrontEndASG will let us decrease desired capacity
[stderr]Putting instance i-eba9fd36 into Standby
[stderr]
[stderr]A client error (ValidationError) occurred when calling the EnterStandby operation: The instance i-eba9fd36 is not in InService.
[stderr]Failed to put instance i-eba9fd36 into Standby for ASG FrontEndASG.
[stderr][FATAL] Failed to move instance into standby

**Comment by bionetmarco** [comment]
I've started to see this issue as well. It was working without a hitch until the last 2 days. I've been seeing "unknown errors" in the Auto-Scaling section of the EC2 dashboard as well.

**Comment by chriskinsman** [comment]
We updated to a newer version of the scripts that properly check for the pending state of the instance and don't attempt to remove it from ELB in that state.  Fixed issue for us...
