### ISSUE TITLE
alternative approach to suspending scaling processes that supports concurrent runs

### ISSUE THREAD

**Issue by simon-weber** [awslabs/aws-codedeploy-samples#51]
The docs note:

> WARNING: If you are using [processes suspend] functionality you should only use CodeDepoyDefault.OneAtATime deployment configuration to ensure a serial execution of the scripts. Concurrent runs are not supported.

To support concurrent runs, we use an alternative approach: suspend/resume around the entire deploy via a deployment group trigger. Here's the code that our lambda function uses; feel free to link it in the docs: https://gist.github.com/simon-weber/285cadb567c11268a15db1b97fe2cbc5.

**Comment by Jmcfar** [comment]
Hi!

 I'll pass the example along to the team. Thanks for the suggestion!
