### ISSUE TITLE
Typo in ELB V2 Readme

### ISSUE THREAD

**Issue by jweberst** [awslabs/aws-codedeploy-samples#52]
There is a typo in the readme for the requirements. It should be:

elasticloadbalancing:DeregisterTargets

instead of

elasticloadbalancing:DeregisterTagets

Its missing an "r" in Targets

Thanks!

**Comment by yubangxi** [comment]
Thanks for pointing this out, it has been fixed in this [commit](https://github.com/awslabs/aws-codedeploy-samples/commit/f06e0d3399ddeeb932853ff47aeb3b551f015683)
