### ISSUE TITLE
Required for Blue / Green deployment groups?

### ISSUE THREAD

**Issue by schmohlio** [awslabs/aws-codedeploy-samples#66]
Hello,

Per the `important-notice-about-handling-autoscaling-processes`, I'm curious if we need to use the scripts in `common_functions.sh` and the `HANDLE_PROCS` configurations when using blue/green deployments with ASGs instead of in-place deployments with ASGs. It seems like since blue/green has native support for autoscaling groups, that it would handle enable/disabling autoscaling events behind the scenes?

Thanks in advance!

**Comment by Jmcfar** [comment]
Hi!

Blue / Green deployments have built-in support for handling ELB interactions, so you should not need to use the provided sample scripts.

**Comment by schmohlio** [comment]
great, thanks.
